server:
  port: 0 # random port

spring:
  application:
    name: user-service

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}} # eureka-server ? display ?? ??
  client:
    fetch-registry: true # eureka server ? ?? ??? ????? ??? ???.
    register-with-eureka: true # eureka ? ??? ???.
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka # registry eureka server end-point